couchbase/fleece

.gitignore, Fleece/Array.cc, Fleece/Encoder.cc, Fleece/KeyTree.cc, Fleece/StringTable.cc, Fleece/Value.cc, Fleece/Value.hh, Fleece/Writer.cc, Fleece/slice.cc, MSVC/Fleece/Fleece.vcxproj, MSVC/Fleece/Fleece.vcxproj.filters, vendor/libb64/cdecode.c, vendor/libb64/cdecode.h, vendor/libb64/cencode.c, vendor/libb64/cencode.h
Note the Array.cc issue.  I can't figure out what is wrong with it.  
The libb64 stuff is because MSVC doesn't allow pointer math on void pointers.
Need to confirm that using vectors and then passing their `data()` is a valid thing to do.
=> Changes for MSVC compilation

Tool/fleece_tool.cc
Because `usage()` banner claimed that
=> Use stdout for decoded output

CMakeLists.txt, Tool/fleece_tool.cc
For simplicity it just compiles library sources statically instead of using shared object.
Also `std:string` constructor of `alloc_slice` declared as explicit, so the tool didn't compile without the second fix. If needed I can do it separately.
=> Build fleece tool with cmake

Fleece/Value.cc
Removed round up so just cast.
Reference: https://github.com/couchbase/couchbase-lite-ios/issues/1764
=> Do not round up when converting from float to int number

Fleece/Value.hh
Compilation fails with clang 3.8.0 on Ubuntu 16.04 like Linux without this change (observed on ElementaryOS Loki).
The error message resolved by this change:
```
/home/mz2/Projects/couchbase-lite-node/vendor/couchbase-lite-core/vendor/fleece/Fleece/Value.hh:51:20: error: default initialization of an object of const type 'const fleece::Null' without a user-provided default constructor
```
=> Fixes a compilation failure with clang 3.8.0.

Fleece/Core/JSONDelta.cc, Fleece/Core/JSONDelta.hh, Tests/DeltaTests.cc
* If diff_match_patch returns a patch range that intersects a UTF-8
multibyte character, the range is adjusted to fall on a character
boundary. This prevents the generated JSON patch string from
containing invalid UTF-8.
* Made gMinStringDiffLength and gTextDiffTimeout changeable.
Fixes #40
=> JSONDelta: Fixed issues with multibyte UTF-8 chars

Fleece/Support/NumConversion.cc
locale.h is conforming POSIX.1‐2008, while xlocale.h is not standard heder and was removed from glibc since version 2.26:
https://sourceware.org/ml/libc-alpha/2017-08/msg00010.html
* The nonstandard header <xlocale.h> has been removed.  Most programs should
use <locale.h> instead.  If you have a specific need for the definition of
locale_t with no other declarations, please contact
libc-alpha@sourceware.org and explain.
So build failed on all recent Linux ditros.
=> fix misside xlocale.h issue

Fleece/Core/SharedKeys.cc, Fleece/Core/SharedKeys.hh, ObjC/Value+ObjC.mm
* include destructor specific to platform, so that CFString can be released
=> CBL-540: fix: memory leak with platform string

API/fleece/Fleece.hh
Before
1. FLSliceResult(fleeceData) creates a copy and retains +1
2. FLDoc_FromResultData holds the alloc_slice, inside FLDoc instance +2
3. (later)FLDoc_Release called and stored alloc_slice, inside FLDoc releases +1
After 
1. FLSliceResult(fleeceData) creates a copy and retains +1
2. FLDoc_FromResultData holds the alloc_slice, inside FLDoc instance +2
3. Release the copy of result from step 1. +1
3. (later)FLDoc_Release called and stored alloc_slice, inside FLDoc releases +1
=> fix: doc leak

Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Tests/EncoderTests.cc
Ensure it won't write an integer key belonging to a different
SharedKeys, which would result in the wrong key string.
(This is a speculative fix, since I haven't seen this occur, but I
have suspicions this might be behind CBSE-7789.)
=> Safety fixes for Encoder::writeKey(Value*)

Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh
Utility to log a backtrace upon an uncaught exception.
=> Added Backtrace::installTerminateHandler()

ObjC/Encoder+ObjC.mm
* when nsexception is thrown from CBL, it is not gettig caught in std::exception
* this fix will handle the nsexception and record the errorCode and message
=> fix: CBL-649: nsexception handled

Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Fleece/Mutable/ValueSlot.cc
Otherwise it may lead to situations where math results are incorrect because both sides turned into ints (e.g. 5.0 / 15.0 != 5 / 15)
=> CBL-978 Disable implicit fleece float -> int conversion

.travis.yml, API/fleece/slice.hh, Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh, cmake/platform_apple.cmake, cmake/platform_linux.cmake
This is for an upstream LiteCore PR of the same name which both removes the support library and makes it easier to link things correctly by having each target export what they need to link with / include rather than having the consuming targets guess.
=> Remove support lib

Fleece/Support/Bitmap.cc, Fleece/Support/endianness.h
The build on MVS 16 2019 for Debug|ARM64 was not working.
=> Fix ARM64 MVS build

Fleece/API_Impl/Fleece.cc, Fleece/Mutable/HeapValue.cc, Fleece/Support/RefCounted.hh
* Optimized Retained's rvalue assignment: I realized it could just do a swap of the two pointers.
* Added a method retain(Retained&&) for use by bridging functions that return a retained raw pointer. Changing `return retain(r.get())` to `return retain(std::move(r))` saves a retain and a release call.
* Plus some whitespace cleanup and comment tweaks.
=> Retained: optimizations

Fleece/Support/ParseDate.cc
The timezone variable is not what would be naturally expected.  Also there doesn't need to be a colon in the offset of the datetime string.
=> CBL-1559: Fix some regressions introduced with datetime

Fleece/Core/JSONConverter.cc, Tests/EncoderTests.cc
Since it doesn't go through the standard "gotError" path.
=> CBL-1763: FLError not set on truncated JSON

Fleece/Support/SmallVectorBase.hh
clang will throw a warning about an unrecognized warning and MSVC doesn't use this at all
=> CBL-1786: Don't ignore unknown warnings with clang

Fleece/Core/SharedKeys.cc, Fleece/Support/ConcurrentMap.cc, Fleece/Support/ConcurrentMap.hh, Tests/SharedKeysTests.cc, Tests/SupportTests.cc
PersistentSharedKeys::revert() was creating a new ConcurrentMap to store the remaining keys, since ConcurrentMap didn't support deletion. Unfortunately that meant that the existing keys had different addresses afterwards, invalidating anything that was holding onto them as slices. That included the Obj-C mutable-Fleece classes.
Fixed this by implementing ConcurrentMap::remove(), which can remove keys in place, removing the need to create a new map.
Recommended reading: Section 4 of ["Concurrent Hash Tables: Fast and General(?)!"](https://arxiv.org/pdf/1601.04017.pdf)
CBL-1707
=> Preserve addresses of shared key strings on txn abort (CBL-1707)

ObjC/slice+CoreFoundation.cc, Tests/ObjCTests.mm
The CoreFoundation callbacks needed to gracefully ignore NULL params.
Added a unit test, verified that it reproduced the reported crash, and that it no longer crashes.
Fixes CBL-1988
=> Fixed crash in alloc_slice::uncopiedNSData()

API/fleece/slice.hh
The constructor `alloc_slice(FLSliceResult &&)` has been marked `explicit` since
commit 777db2 on Feb 25. I don't know why that change was made. Jianmin just
discovered that our many implicit conversions from an FLSliceResult rvalue to
an alloc_slice are now leaking as a result -- they now call the _lvalue_
reference version, which does not release the FLSliceResult.
I removed `explicit` from the rvalue-ref version and added it to the lvalue-ref
version. This required only two small source changes in LiteCore, and the
LiteCore tests still pass.
(The `explicit slice(const FLSliceResult&)` constructor I added is to fix some
conversions in LiteCore that were apparently using alloc_slice as an
intermediate, and broke when I made the lvalue version explicit.)
=> Fixed leak-producing FLSliceResult -> alloc_slice conversions

Fleece/Mutable/ValueSlot.cc, Fleece/Mutable/ValueSlot.hh
The prior size optimization in ValueSlot used the high byte of the
`_pointer` field to distinguish between an actual pointer and an
inline 7-bit Value; it assumed if the upper byte is zero then it's a
pointer.
This isn't true anymore in Android: "Starting in Android 11, for 64-
bit processes, all heap allocations have an implementation defined tag
set in the top byte of the pointer on devices with kernel support for
ARM Top-byte Ignore (TBI)."
Switched to using the _low_ byte as a tag, with a value of 0xFF
denoting inline, and anything else being a pointer. This works because
any Value* we store there must have at least one zero bit in the
LSB; see the comment in ValueSlot.hh for details.
=> Fixed Android 11 incompatibility with ValueSlot ptr tagging

API/fleece/Fleece.h, API/fleece/Fleece.hh, Fleece/API_Impl/Fleece.cc, Fleece/Core/Doc.cc, Fleece/Core/Doc.hh
This provides a reasonably type-safe way to associate a client object with a Fleece `Doc` (`FLDoc`), and thereby with any Value.
For details see the doc-comments in Fleece.h.
This is for use by Couchbase Lite C, for looking up a CBLBlob object given an FLDict in a query result set.
=> FLDoc: Added get/set associated pointer API

Fleece/Support/Base64.cc, Tests/SupportTests.cc, vendor/libb64/cdecode.c
Add one extra bytes to the output buffer as required by the decoder when it reports the ending position for the case that the buffer size is exactly the same size as the output.
CBL-2264
=> Fix buffer overflow when decoding base64 string

Fleece/Core/Doc.cc
* Windows debug mode is not enable string pooling optimization by default. Also it seems to be fragile to compare the pointer even though most of the case the string will be constant or literal.
* Fixed the issue to use strcmp in Doc::setAssociated() and in Doc::getAssociated() as a fallback.
=> Fix string comparison failed on Windows under debug mode

Fleece/Core/Doc.cc
Do not register scopes of size-2 slice, CBSE-10529
Values of size 2 are simple values in that they don't have sub-values. Therefore, they don't provide interesting scope. An exception is the empty dict. We use the empty dict for empty revision bodies of databases and apply technical check, c.f. DatabaseImpl::validateRevisionBody().
We are mostly concerned of the pre-encoded size-2 values, such as Value::kTrueValue, etc. Their address ranges are constant, regardless of the associated scope, causing the failure of the assertion of, "Incompatible duplicate Scope."
However, we should *always* register the scope if this is a Doc.
=> Do not register scopes of size-2 slice, CBSE-10529 (#107)

Fleece/Core/JSONConverter.cc, Fleece/Support/NumConversion.cc, Fleece/Support/NumConversion.hh, Tests/EncoderTests.cc, Tests/NumericTests.cc
The existing ParseDouble is dumber than ParseInteger, as it doesn't do any error checking. Added a new version that does.
=> NumConversion: Improved ParseDouble

API/fleece/slice.hh
```
fleece/API/fleece/slice.hh:212:9: error: non-static data member cannot be constexpr; did you intend to make it const?
constexpr pure_slice(nullptr_t) noexcept             :pure_slice() {}
^~~~~~~~~
const
```
=> fix build error with clang 12.0.1

API/fleece/Mutable.hh, Tests/API_ValueTests.cc
* Added fleece::RetainedArray and RetainedDict in companion with the existing fleece::RetainedValue but specifically for Array and Dict.
* The API and implementation are based on fleece::RetainedValue.
* This is related to CBL-2572 that a CBL-C++ requires to return a retained fleece::Array.
=> CBL-2615 : Add fleece::RetainedArray and RetainedDict

Fleece.xcodeproj/project.pbxproj
On ARM Macs Homebrew installs into /opt/homebrew instead of /usr/local
(apparently so you can have both ARM-native and emulated x86 stuff?)
This directory isn't in the $PATH of shells run by Xcode, even if you
add it to ~/.bashrc.
This means if you've used Homebrew to install Doxygen on an ARM Mac,
Fleece's Build Documentation phase won't find it and does nothing.
I worked around this by updating the Build Documentation script to
prepend /opt/homebrew/bin to the PATH when it starts.
=> Xcode: Workaround for finding doxygen on ARM Macs

API/fleece/FLSlice.h, API/fleece/Fleece.hh, API/fleece/slice.hh, Fleece/Support/Backtrace.cc, Fleece/Support/ConcurrentMap.cc, Fleece/Support/SmallVector.hh, Fleece/Support/SmallVectorBase.hh, Fleece/Support/StringTable.cc, Fleece/Support/endianness.h, cmake/platform_base.cmake
Fix the most dangerous and easy to fix gcc/clang warnings.
The most of them in includes so I get them when I use fleece as external library.
For "strict aliasing violation" I confirm that my fix do not change assembly (on optimization level -O2 | /O2) for clang/gcc/msvc (amd64).
=> Fix warning

Fleece/Support/Backtrace.cc
Was an error in Xcode but not CMake because the latter does not
enable `-Wshorten-64-to-32`.
Fixes #142
=> Fixed implicit-conversion error from previous commits (#142)

API/fleece/Mutable.hh, Tests/API_ValueTests.cc
A boolean test of a mutable array/dict property, like
`if (dict["key"])`, would always evaluate to true; there was an
incorrect implicit conversion from `keyref` to `FLSlot` that made
the test evaluate to a non-NULL FLSlot pointer.
Removing the FLSlot conversion operator fixed it. I couldn't deduce
any need for the operator, and removing it didn't break anything in
LiteCore or CBL-C.
I did add a setNull() method, for parity with Slot.
Fixes #105
=> Fixed a bad implicit conversion with mutable operator[] (#105)

Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh
During a crash, rather than just printing the PC address, use backtrace_symbols to print out a usable offset that can be later used with addr2line
=> Utilize backtrace_symbols to get more information

Fleece/Support/Backtrace.cc
In <execinfo.h>, the second parameters of backtrace() and
backtrace_symbols() are int, not size_t. This caused a warning/error
at line 357 in Xcode.
=> Fixed another implicit conversion error in Backtrace.cc

API/fleece/Fleece.h, Fleece/API_Impl/Fleece.cc, Fleece/Support/Fleece.exp
I found there wasn't any way (through the public API) to store a
date-time string into a MutableDict; the only API for writing a
timestamp was on FLEncoder. There also wasn't an equivalent of
`c4_now`.
* FLTimestamp_Now(), returns the current timestamp
* FLTimestamp_ToString(), creates a date-formatted string
* FLTimestamp_FromString(), parses a date string
=> Added some date/time API functions

Fleece/Core/Dict.cc, Fleece/Core/Dict.hh, Fleece/Mutable/HeapDict.cc
If a HeapDict's overlay map stores the string form of a key, but its
parent Dict uses the int form, iteration will find _both_ forms of the
key. This is obviously bad news.
Fixed this by making sure that when a new entry is added to the
overlay map, it uses the same form of key as found in the parent Dict.
(It used to just look the key up in the SharedKeys, but that's not
enough in the edge case where the in-memory SharedKeys are not up to
date and the parent Dict uses a key that's not in memory.)
CBL-2844
=> Fixed incorrect iteration of HeapDict due to key mixup

Fleece/Core/Pointer.hh, Fleece/Support/ConcurrentMap.hh
Fix warnings that produces clang with "-Wcast-align" flags:
```
cast from 'uint8_t *' (aka 'unsigned char *') to 'uint16_t *' (aka 'unsigned short *') increases required alignment from 1 to 2 [-Wcast-align]
ast from 'uint8_t *' (aka 'unsigned char *') to 'uint32_t *' (aka 'unsigned int *') increases required alignment from 1 to 4 [-Wcast-align]
warning: cast from 'fleece::ConcurrentMap::Entry *' to 'uint32_t *' (aka 'unsigned int *') increases required alignment from 2 to 4 [-Wcast-align]
```
The result of cast from pointer with one align to pointer with another align is unspecified
in C++ and undefined behavior in C. So I think it worth to fix,
plus it should be zero cost, because of `memcpy` with fixed size inlined by all modern C++ compilers.
Not fixed:
```
FLSlice.cc:144:16: warning: …
```
=> fix some warnings about "cast increases required alignment"

API/fleece/CompilerSupport.h, API/fleece/FLBase.h, API/fleece/FLExpert.h, API/fleece/FLSlice.h
* Moved FLEECE_PUBLIC (from FLBase.h) and FLAPI (from FLSlice.h) to CompilerSupport.h to avoid circular includes.
* Fixed missing FLEECE_PUBLIC tagging
=> Fix missing FLEECE_PUBLIC tagging

API/fleece/FLExpert.h, Fleece/API_Impl/Fleece.cc, Fleece/Support/JSONEncoder.hh
This helps generate output in the common JSON-object-per-line format. (Does it have an official name?)
I'm using this format in Connected Client for query results.
=> Added FLJSONEncoder_NextDocument()

Fleece/Core/Doc.cc, Tests/ValueTests.cc
This PR changes the container which stores `Scope` `memEntry`s from a vector to a multiset to improve performance for registering and unregistering `Scope`s.
The complexity of finding `memEntry`'s in a multiset is the same as for a vector (both logarithmic). Insertion and removal, on the other hand, is linear for vectors and logarithmic for multisets.
Note that multisets maintain insertion order for elements that compare as equal and are therefore equivalent to the previously used vector.
[This issue](https://github.com/couchbase/couchbase-lite-C/issues/285) contains more information on the motivation for this change.
=> Use `std::multiset` for `Scope` memory map

Fleece/Core/Dict.cc, Fleece/Core/Dict.hh, Fleece/Mutable/HeapDict.cc
If a HeapDict's overlay map stores the string form of a key, but its parent Dict uses the int form, iteration will find _both_ forms of the key. This is obviously bad news.
Fixed this by making sure that when a new entry is added to the overlay map, it uses the same form of key as found in the parent Dict. (It used to just look the key up in the SharedKeys, but that's not enough in the edge case where the in-memory SharedKeys are not up to date and the parent Dict uses a key that's not in memory.)
=> CBL-2867: Fixed incorrect iteration of HeapDict due to key mixup

API/fleece/Fleece.hh, Fleece/API_Impl/Fleece.cc
It uses an aurgument of FLSliceResult, but fails to release it. The leak is found by valgrind.
=> CBL-3366 : FLDoc_FromResultData leaks memory

Fleece/Core/Dict.cc, Fleece/Core/SharedKeys.hh
A transaction might be rolled back, potentially leaving an invalid shared key in a `Dict::key`.
Related issue: https://github.com/couchbase/couchbase-lite-C/issues/287
=> Don't cache `Dict::key::_numericKey` when `SharedKeys` is in transaction

Fleece/Core/Dict.cc, Fleece/Core/SharedKeys.hh
Port from the master branch (https://github.com/couchbase/fleece/commit/dcaa54943e6fcf05a610476912299873b5328bf7) for 3.0.6-MR.
A transaction might be rolled back, potentially leaving an invalid shared key in a `Dict::key`.
=> CBL-3833 : Don't cache `Dict::key::_numericKey` when `SharedKeys` is in transaction (Port)

Fleece/Core/Doc.cc, Fleece/Mutable/HeapValue.cc, Fleece/Support/Backtrace.cc, Fleece/Support/ConcurrentArena.cc, Fleece/Support/ConcurrentMap.cc, Xcode/xcconfigs/FleeceTest.xcconfig, Xcode/xcconfigs/Project.xcconfig
Required for both CBL-4471 (berrylium) and CBL-4606 (helium) in order to be able to build Core with latest version of Xcode.
=> CBL-4471: Xcode 14.3 unqualified calls to std::move

Xcode/xcconfigs/Project.xcconfig
IPHONEOS_DEPLOYMENT_TARGET                         = 11.0
MACOSX_DEPLOYMENT_TARGET                           = 10.14
TVOS_DEPLOYMENT_TARGET                             = 11.0
As are requested by CBL 4631
=> Update Apple's configurations:

Fleece/Core/Doc.cc, Fleece/Mutable/HeapValue.cc, Fleece/Support/Backtrace.cc, Fleece/Support/ConcurrentArena.cc, Fleece/Support/ConcurrentMap.cc, Xcode/xcconfigs/FleeceTest.xcconfig
Looks like Core release branch requires Fleece submodule points to matching release branch.
This is merged from master up to the point required for CBL-4824, which is the Xcode 14.3 fixes that allow Core to build.
=> CBL-4824: Move fixes for 3.1.2 from `next/3.1` to `release/3.1`

Fleece/API_Impl/Fleece.cc, Tests/SupportTests.cc
Ported from CBL 4470 of Beryllium.
=> CBL-4508: Fix a bug in FLTimestamp_ToString

API/fleece/FLExpert.h, Fleece/Mutable/HeapDict.cc, Fleece/Mutable/HeapDict.hh, Fleece/Mutable/MutableDict.hh, Fleece/Support/slice_stream.hh
1. Fixed a crash in Dict::mutableCopy() using kCopyImmutables
2. Make slice_istream moveable (just added default move ctor/assign)
3. Expose impl constant Trust::kDontParse in FLExpert.h
=> Three fixes needed for latest LiteCore VV work

Fleece/Support/ParseDate.cc
Andriod build gives compile warning / error for the cast from `long long` to `long`. I'm surprised no other compiler, or IDE static analysis, gave this warning.
=> CBL-59: Android build fix.

Fleece/Core/Dict.cc, Tests/ValueTests.cc
If a dict iterator is at the end, calling key() or value() is safe but keyString() crashes. Let's fix that.
Also added some sanity checks of iterators on empty collections, which includes a test of this fix.
=> Fixed crash calling DictIterator::keyString

Fleece/Support/NumConversion.hh
Fixed static analyzer warnings in NumConversion.hh. The "condition always true" and "condition always false" warnings can be avoided by using `if constexpr`, so those asserts aren't even compiled when they're not relevant.
=> Fixed a static analyzer warning

Fleece.md, Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Fleece/Core/Internal.hh, Fleece/Core/Value.cc, Fleece/Core/Value.hh, Fleece/Mutable/ValueSlot.cc, Fleece/Mutable/ValueSlot.hh, Tests/EncoderTests.cc, Tests/MutableTests.cc
Some `double` numbers stored in Fleece would be improperly rounded (too few digits of precision) when written to JSON or otherwise converted to strings.
The fix makes a slight change to the Fleece binary format, using a previously unused bit in a float value, but it's backwards compatible.
Fixes #206
=> Fix loss of precision encoding some double values to JSON (#206)

Fleece/Core/Dict.cc, Tests/ValueTests.cc
If a dict iterator is at the end, calling key() or value() is safe but keyString() crashes. Let's fix that.
Also added some sanity checks of iterators on empty collections, which includes a test of this fix.
=> Fixed crash calling DictIterator::keyString (#205)

Xcode/xcconfigs/Project.xcconfig
We are bumping the iOS target version to 12.0 in Beryllium.
=> CBL-5379 : Update iOS Deployment Target to 12.0

Fleece/Support/ParseDate.cc
CBL3.1 formats timezone as `+0500`, rather than `+05:00`. Restore behaviour to match CBL3.1
=> CBL-5488: DateTime Timezone offset inconsistent

API/fleece/FLCollections.h
There's been confusion about the proper way to iterate Arrays and Dicts in the C API. I've updated the doc-comments on those functions to try to make it clearer.
I wish I could change the Next functions to return void, but that would be an incompatible change to CBL-C. Instead I just removed the description of the return value and added a warning about illegal calls.
=> Added doc-comments clarifying use of FLArray/FLDict iterators

CMakeLists.txt, Fleece/Support/betterassert.cc, Xcode/xcconfigs/Project.xcconfig
Defining `_LIBCPP_REMOVE_TRANSITIVE_INCLUDES` stops libc++'s headers from including other libc++ headers except as defined in the language standard. This is a good idea because it will catch situations where a header isn't explicitly included, which will cause build errors with other standard libs like GCC's and MSVC's.
=> Define _LIBCPP_REMOVE_TRANSITIVE_INCLUDES

Tests/ObjCTests.mm
In Jenkins' build machine (MacOS), we found it failed to convert UINT64_MAX to unsigned with @() after we upgraded MACOSX_DEVELOPMENT_TARGET to 12 from 10.14.
A test is falied because of it. Fix it by explicit cast.
=> Explicit convert UINT64_MAX to unsigned

Tests/ObjCTests.mm
In Jenkins' build machine (MacOS), we found it failed to convert UINT64_MAX to unsigned with @() after we upgraded MACOSX_DEVELOPMENT_TARGET to 12 from 10.14. A test failed because of it. Fix it by creating an NSNumber with unsignedLongLong.
=> Explicit convert UINT64_MAX to unsigned.

API/fleece/CompilerSupport.h, API/fleece/slice.hh, Fleece/Core/Dict.hh, Fleece/Core/Doc.hh, Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Fleece/Core/JSONConverter.hh, Fleece/Core/JSONDelta.cc, Fleece/Core/JSONDelta.hh, Fleece/Core/Path.hh, Fleece/Mutable/HeapArray.hh, Fleece/Mutable/HeapDict.hh, Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh, Fleece/Support/NumConversion.cc, Fleece/Support/NumConversion.hh, Fleece/Support/Writer.hh, Fleece/Support/slice_stream.hh, Fleece/Support/varint.hh
Many of the warnings that nonnull GCC spews out seem to come from Fleece. 
Looks like there's a TODO item to replace NONNULL with FL_NONULL, so I've done that. 
Hopefully that addresses the GCC warnings.
=> CBL-5686: Fix GCC 'nonull' warnings

Fleece/Core/JSONConverter.cc, Tests/ValueTests.cc
This requires to increase the static limit of depth that the JSON parser can handle.
=> CBL 5594 : Increase Rev Tree Depth Limit to 100.

API/fleece/CompilerSupport.h, API/fleece/slice.hh, Fleece/Core/Dict.hh, Fleece/Core/Doc.hh, Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Fleece/Core/JSONConverter.hh, Fleece/Core/JSONDelta.cc, Fleece/Core/JSONDelta.hh, Fleece/Core/Path.hh, Fleece/Mutable/HeapArray.hh, Fleece/Mutable/HeapDict.hh, Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh, Fleece/Support/NumConversion.cc, Fleece/Support/NumConversion.hh, Fleece/Support/Writer.hh, Fleece/Support/slice_stream.hh, Fleece/Support/varint.hh
Fixes #227
- Backed out commit cf840529e9045f41d9365178b2368cf034dcb0aa
- Fixed the FL_NONNULL etc. macros to be defined only with Clang
=> Fix broken Xcode build & nullability macros

Fleece/API_Impl/Fleece.cc, Tests/API_ValueTests.cc
Ensure you can still get the error message from an encoder after calling Finish on it.
Fixes #229
=> Fix FLEncoder_GetErrorMessage call after FLEncoder_Finish [#229]

API/fleece/CompilerSupport.h, API/fleece/FLMutable.h, API/fleece/Fleece+CoreFoundation.h, API/fleece/Mutable.hh, API/fleece/PlatformCompat.hh, Fleece.xcodeproj/project.pbxproj, Fleece/API_Impl/Fleece.cc, Fleece/Core/Builder.cc, Fleece/Core/Builder.hh, Fleece/Support/slice_stream.hh, ObjC/Encoder+ObjC.mm, Tests/BuilderTests.cc, cmake/platform_base.cmake
These functions let you create complex nested Fleece structures with
a single call. It's basically JSON with values substituted from
arguments using printf-style "%" specs. You can
* Create a mutable array or dict
* Add to an existing mutable array or dict
* Write to an encoder
See doc-comments in Fleece.h for details. BuilderTests.cc has a bunch of examples.
----
Unlike the existing `FLEncoder_WriteCFObject`, these functions create
mutable object trees. They're needed by the formatted builder so it
can accept complex CF/NS values using the `%@` specifier.
=> API: Added printf-style formatted builder functions

Fleece/Support/Backtrace.cc, Fleece/Support/Backtrace.hh, Tests/SupportTests.cc
There was a dumb typo, maybe mine, that prevented some uses of Backtrace from capturing any stack frames.
This explains why the terminate handler isn't logging a backtrace.
=> Fixed Backtrace terminate handler not capturing any frames

Fleece/Core/Value.cc, Fleece/Core/Value.hh, Fleece/Mutable/HeapValue.cc, Fleece/Mutable/HeapValue.hh, Fleece/Mutable/ValueSlot.hh, Tests/MutableTests.cc
This is a bandaid for a nasty architectural bug (#223)
Retaining still doesn't work, but it now throws an exception instead of overwriting out-of-bounds memory.
=> Partial fix for retaining Inline scalar in mutable container [#223]

API/fleece/FLEncoder.h, API/fleece/Fleece.hh, Fleece.xcodeproj/project.pbxproj, Fleece/API_Impl/FLEncoder.cc, Fleece/API_Impl/Fleece+ImplGlue.hh, Fleece/API_Impl/Fleece.cc, Fleece/Core/Builder.cc, Fleece/Core/Builder.hh, Fleece/Core/Encoder.hh, Fleece/Core/JSLexer.hh, Fleece/Support/Fleece.exp, Fleece/Support/JSONEncoder.cc, Fleece/Support/JSONEncoder.hh, ObjC/Encoder+ObjC.mm, Tests/BuilderTests.cc, cmake/platform_base.cmake
C API additions:
```c
/** Writes an Array or Dict to the encoder, as per the format string and printf-style arguments.
For details, see documentation of \ref FLValue_NewWithFormat. */
FLEECE_PUBLIC bool FLEncoder_WriteFormatted(FLEncoder, const char* format, ...) FLAPI __printflike(2, 3);
/** Writes an Array or Dict to the encoder, as per the format string and `va_list`.
For details, see documentation of \ref FLValue_NewWithFormat. */
FLEECE_PUBLIC bool FLEncoder_WriteFormattedArgs(FLEncoder, const char* format, va_list args) FLAPI;
```
C++ API additions:
```c++
class Encoder {
...
inline bool writeFormatted(const char* format, ...) __printflike(2, 3);
inline bool writeFormattedArgs(const char* format, va_list args);
```
> FYI, this is a dependency of the LiteCore changes-feed PR …
=> Add "printf" support to Encoder

vendor/catch/CaseListReporter.cc
It thought `//<< _sectionStats...` looked like a (badly-formatted) doc comment.
=> Fixed minor compiler warning from catch3 PR

API/fleece/Expert.hh, API/fleece/FLExpert.h, API/fleece/FLJSON.h, API/fleece/FLMutable.h, Documentation/Doxyfile, Documentation/Doxyfile_C++, Fleece.xcodeproj/project.pbxproj
- Removed obsolete properties from Doxyfile
- Removed a \ref in Expert.hh that doxygen couldn't identify because it's to a C function, and the Doxyfile_C++ doesn't include the C headers.
- Made Xcode run doxygen if either Doxyfile has been touched.
- Fixed Xcode 15 settings nags, while I was at it
=> Fixed doxygen warnings

API/fleece/CompilerSupport.h
* Moved the definition of LIFETIMEBOUND to be next to FLAPI.
* Aligned formatting with the other sections by moving # to the front of the lines.
=> CBL-6485 : Define LIFETIMEBOUND only for C++

.github/workflows/cmake.yml
Bit of boilerplate to cancel running actions when a branch is updated.
https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions
=> GitHub Actions: Added `concurrency`

Fleece/Support/RefCounted.cc, Fleece/Support/SmallVector.hh
Iterating an empty smallVector triggers a UBSan warning about "forming a reference to nullptr".
`_get()` returns a reference to the first item; when the vector is empty the first item could point to nullptr. So avoid using `_get` in `begin()` / `end()`, which just take the address of the reference anyway. Calling `_begin()` instead is simpler.
A second commit snuck in :) that just resolves a GCC warning about ignoring the return value of `asprintf`.
=> Avoid UBSan error iterating empty SmallVector

API/fleece/InstanceCounted.hh
because of bugs gcc/clang accept this before,
but now clang 19.x gives compile time error,
because of "untack" method is private:
https://godbolt.org/z/hd9n1o3br
=> fix calling base class private method

API/fleece/CompilerSupport.h, Fleece/API_Impl/Fleece.cc
From now on use FLEECE_PUBLIC_IMPL on the implementations of symbols.
See also https://github.com/couchbase/couchbase-lite-core/pull/2258
=> Fixed FLEECE_PUBLIC to avoid GCC attribute warnings

API/fleece/RefCounted.hh, API/fleece/slice.hh, CMakeLists.txt, Fleece/Support/RefCounted.cc, Fleece/Support/SmallVector.hh, Fleece/Support/slice_stream.hh
Best to look at each of the 5 commits individually:
Simply adds three utility methods. These are useful for using a smallVector as a lightweight set (for small sizes obviously.)
`retained_cast<T>(U)` is equivalent to `dynamic_cast` except its parameter and result are Retained values not raw pointers.
Fixes a build error in Clang 16. [I've actually made this a separate PR, #263, since it's broken the master branch.]
Helps detect some additional dangling-pointer errors, by adding the LIFETIMEBOUND attribute for conversions from alloc_slice to slice. This tells Clang that the resulting slice's lifetime must not exceed the original alloc_slice's.
There are some other changes that are just to fix some annoying compiler errors triggered by the above.
OK, this one is cool! I added a second …
=> Improvements from the P2P work

API/fleece/RefCounted.hh
Explicitly use std::nullptr_t to resolve build failures, as clang on Debian 11 does not provide nullptr_t in the global namespace.
=> Fix nullptr_t not defined error with clang on Debian 11

API/fleece/RefCounted.hh, CMakeLists.txt
- RefCounted.hh needs to include the header that defines `std::nullptr_t`
- Disabled new warnings that complain about identifiers or macros beginning with an underscore
PR https://github.com/couchbase/couchbase-lite-core/pull/2351 depends on this one.
=> Fixed Xcode 26 / Clang 17 build errors
