couchbase/fleece

.gitignore, Fleece/MSVC_Compat.hh, Fleece/slice.hh, MSVC/Fleece/Fleece.vcxproj, MSVC/Fleece/Fleece.vcxproj.filters
=> Fix windows

CMakeLists.txt, Fleece/PlatformCompat.hh, Fleece/slice.cc
Changes for CMake on Windows and some additional platform defines
=> Cmake windows

Fleece/PlatformCompat.cc, Fleece/PlatformCompat.hh
Abstract file operations into UTF-8 safe ones
=> Fix utf8 windows

Fleece/Fleece.h
This fixes an issue when linking together 2 or more files both of which include the header fleece.h
=> VS2017 improvements

Deltas.md
Based on my reading of the delta format spec and the other examples, this delta example seems to be using the wrong type of brackets.
=> Fix incorrect brackets on delta array example

CMakeLists.txt, Fleece.xcodeproj/project.pbxproj, Fleece/Mutable/HeapValue.cc, Fleece/Mutable/HeapValue.hh, Fleece/Mutable/ValueSlot.cc, Fleece/Mutable/ValueSlot.hh, Fleece/Support/Bitmap.cc, Fleece/Support/Bitmap.hh, Fleece/Support/FileUtils.cc, Fleece/Support/FleeceException.cc, Fleece/Support/diff_match_patch.hh, Fleece/Support/sliceIO.cc, Fleece/Tree/HashTree+Internal.hh, Fleece/Tree/HashTree.cc, Fleece/Tree/HashTree.hh, Fleece/Tree/MutableNode.hh, MSVC/asprintf.c, MSVC/asprintf.h, MSVC/vasprintf-msvc.c, Tests/SupportTests.cc, Tool/fleece_tool.cc, appveyor.yml, build_cmake/build.ps1
Still one error remains.  vasprintf is not available, and is not defined in the scope of Fleece.  Is it OK to depend on the one from LiteCore?
=> Fix errors building with Windows

Experimental/KeyTree.cc, Fleece/Support/Backtrace.cc
This makes compiling fleece for Android with gcc possible.
=> fix compilation with gcc on Android

Tests/DeltaTests.cc
Added more delta unit test cases.
---
I've left a new failing test commented out, as it looks like a problem with the underlying diffmatchpatch library, rather than the Fleece wrapper. Further testing may be required to find out exactly why.
```
old: "モバイルデータベースは将来のものです。 ある日、私たちのデータが端に集まります。"
new: "モバイルデータベースがここにあります。 あなたのデータはすべて端にあります。"
JS/Go delta: "30=76-70+がここにあります。 あなたのデータはすべて端にあ|12=\"
C++ delta:   "32=47-35+ここにあります。 あなた|14=1-10+すべて|6=3-2=1-1+|12="
```
Looking closely at the delta, you can see some bits that don't make sense, like: `1+|`. I suspect UTF-8 chars are being split in-between their boundaries, resulting in bytes that don't make any sense on their own.
=> Add more delta unit test cases

Fleece/Support/ParseDate.cc
1. UTC is always picked up as "invalid time zone" which affects the date result
2. The default for no time zone should be system time zone
=> Fix some edge cases in ParseDate

Fleece/Support/InstanceCounted.hh
Fix build with gcc for debug case.
=> fix build with gcc: missed include for size_t

Fleece.xcodeproj/project.pbxproj
* flag to ignore conversion error.
=> fix: xcode 10.x flag

Fleece/Core/JSONConverter.cc, Tests/EncoderTests.cc
=> Fix issue 59

Xcode/xcconfigs/Project.xcconfig
* SDKROOT = iphoneos to make it compatible with catalyst
=> make catalyst compatible

ObjC/Encoder+ObjC.mm
* handle json encoder to handle ObjC types
* combined calls to a single function `encodeTo:`
=> handle json encoder to handle ObjC types

API/fleece/Base.h, API/fleece/Mutable.hh, API/fleece/slice.hh, Fleece/Support/Base64.cc, Fleece/Support/PlatformCompat.hh, Fleece/Support/slice.cc
This required some shifting around of a few things like hot, cold, and stepover.
=> Remove includes of private headers from public ones

API/fleece/Fleece.h
Simple inlines to avoid having to cast to (FLValue)
=> API: Added FLSlot_SetArray, FLSlot_SetDict

Fleece/API_Impl/Fleece+ImplGlue.hh, Fleece/API_Impl/Fleece.cc, Tests/EncoderTests.cc
=> Fix bugs in FLEncoder after reset().

API/fleece/Fleece.h, Fleece/API_Impl/Fleece.cc, Tests/MutableTests.cc
The new mutables are resursively mutable, that is, all nested arrays and dicts are also mutable.
=> Add functions to create mutable dict/array from JSON. CBL-2358

API/fleece/FLMutable.h
=> Add the missing closing group curly bracket

CMakeLists.txt, cmake/platform_apple.cmake, cmake/platform_base.cmake, cmake/platform_linux.cmake, cmake/platform_win.cmake
Buffer overrun checks, stack protector, and control guard (Windows)
=> Enable compile and runtime hardening

Fleece/Core/JSONDelta.cc, Fleece/Core/Value+Dump.cc, Fleece/Core/Value.cc, Fleece/Support/JSONEncoder.cc, Fleece/Support/JSONEncoder.hh, Fleece/Support/NumConversion.hh, Fleece/Support/Stopwatch.hh, Fleece/Tree/HashTree.cc, Fleece/Tree/MutableNode.hh, Tests/EncoderTests.cc, Tests/FleeceTests.cc, Tests/HashTreeTests.cc, Tests/SharedKeysTests.cc, Tests/SupportTests.cc
Cherry-picked snprintf changes from CBL-3669 onto this branch.
=> CBL-3712: Backport snprintf changes to Lithium

Fleece.xcodeproj/project.pbxproj
=> Add build configuration Test_EE based on Debug_EE

API/fleece/FLExpert.h, Fleece.xcodeproj/project.pbxproj, Fleece/API_Impl/Fleece.cc, Fleece/Core/Encoder.cc, Fleece/Core/Encoder.hh, Fleece/Support/SmallVector.hh, vendor/catch/CaseListReporter.hh, vendor/catch/catch.hpp
Sorry if it's awkward having these in one PR, but it seemed a lot less work than creating five separate branches with their own PRs.
It's best to review each commit separately. They're all pretty small.
=> Some improvements/fixes needed for my VersionVector work

API/fleece/FLKeyPath.h
Actually, the problem manifested in CBL 4795 is fixed in the SQL++ parser.
=> CBL-5132: Updating fleece doc re. FLKeyPath

Fleece/API_Impl/Fleece.cc, Fleece/Core/Encoder.cc, Fleece/Support/JSONEncoder.cc, Fleece/Support/ParseDate.cc, Fleece/Support/ParseDate.hh
Rebased feature/parse_date_parts onto master.
=> CBL-59: Supporting date parsing functions

Fleece/Support/ParseDate.cc
Some small supporting changes in Fleece.
Actually a decent improvement too as I've reduced some code duplication.
=> CBL-5377: MILLIS_TO_STRING returning UTC instead of local timezone

Fleece.xcodeproj/xcshareddata/xcschemes/Fleece Test Optimized.xcscheme, Fleece.xcodeproj/xcshareddata/xcschemes/Fleece Test.xcscheme, Fleece.xcodeproj/xcshareddata/xcschemes/Fleece Tool.xcscheme
Literally no changes besides `LastUpgradeCheck = 1600`
=> Dismiss Xcode 16 nags

licenses/APL2.txt, licenses/BSL-Couchbase.txt
Change-Id: I1c2d5537cd42c2bc19b9b2542b7884b9947a053d
=> CBD-6163: BSL License updates - Couchbase Lite Version 3.1
